### ISSUE TITLE
Author Name Font & Size

### ISSUE THREAD

**Issue by raisinahill** [claudiosanches/author-bio-box#11]
Hi! 

I installed the plugin author bio box and it looks awesome. My website under reference is https://raisinahill.com/

However, I was just thinking if I can reduce the font size of the author name and also be able to choose my font to display the author name! 

Can you please help? 

Thanks in advance. 

Best. 

Neeraj

**Comment by claudiosanches** [comment]
You can just use the Customizer "Custom CSS" option to change this things.

**Comment by raisinahill** [comment]
Thanks. We figured it out. Thanks again for your reply.
