### ISSUE TITLE
Author box is displaying on all custom post types

### ISSUE THREAD

**Issue by rumspeed** [claudiosanches/author-bio-box#4]
I am using _Sugar Events Calendar_ on an installation along with _Author Bio Box_. At the bottom of the single event pages, the Author Bio Box appears and I want to filter that out. Technically, it's a post... but not a blog post (post_type=sc_event) and I would like to remove it on all event pages. It is also appearing at the bottom of a few other custom post types I am using.

On the plugin setting page you can choose to display "Only in Posts" which reads as if it relates to blog posts and not all custom post types. The code where this setting is used isn't looking for just blog, but just if it **is_single()**.

```
        if ( 'posts' == $settings['display'] ) {
            $display = is_single();
        } else if ( 'home_posts' == $settings['display'] ) {
            $display = is_single() || is_home();
        }
```

Maybe that is by design but it is a bit misleading. How about adding a selection for "Just blog posts"?

Another possibility is to use your new filter. I see the latest release has a filter, **authorbiobox_display**.  Can this be used to filter out all post types except **post_type=post**?

**Comment by robsonw** [comment]
Thanks for gist @rumspeed . Work like a charm. All the Best.

**Comment by rumspeed** [comment]
Great. I'm glad it worked for you, @robsonw. Cheers!
